apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "message-simulator.fullname" . }}
  labels:
    {{- include "message-simulator.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          # Route API traffic to the backend Spring Boot Service
          - path: /v1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "message-simulator.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          
          # Route all other root traffic to frontend Service
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "message-simulator.fullname" . }}-frontend
                port:
                  number: 8080
