apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "message-simulator.serviceAccountName" . }}
  labels:
    {{- include "message-simulator.labels" . | nindent 4 }}
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/message-simulator-irsa
